* howto

** build

This builds a static website.  All the website files are pushed in the
subdirectory =_site=.
#+BEGIN_EXAMPLE
make
#+END_EXAMPLE

** push the built website files

The subdirectory =site= is a git submodule.  Its contents are synced
from the contents of subdirectory =_site=.  The purpose of the =site=
submodule is to be pushed on remote repository services such as github
pages, for hosting static websites.

* todo list

******** TODO éléments pour mettre à jour le site perso
    :PROPERTIES:
         :TRIGGER:  chain-find-next(TODO,todo-only)
         :END:

cf. le site de Karine

Thématiques de recherches :

    Sécurisation de code : schéma de protection et automatisation de l'insertion dans le flot de compilation
    Analyse de robustesse de code assembleur/binaire par vérification formelle de
    Optimisation de code
    Exploitation efficace de many-coeurs

Publications

Projets de recherche

    ANR PROSECCO 2015-2019 (Coordinatrice).
    ANR MORE 2007-2010 : Multicriteria Optimizations for Real-time Embedded systems.

http://www-soc.lip6.fr/~heydeman/

******** MAYBE à lire: blog post. Hakyll setup and initial customization
    CLOSED: [2018-11-07 mer. 22:04]
  - State "MAYBE"      from              [2018-11-07 mer. 22:04]

  https://robertwpearce.com/hakyll-pt-1-setup-and-initial-customization.html

** biblio refs

******** MAYBE expand abstracts - show abstracts and citations
    CLOSED: [2018-08-13 lun. 10:48]
    :PROPERTIES:
  :TRIGGER:  chain-find-next(TODO,todo-only,from-bottom)
  :END:
  - State "MAYBE"      from "TODO"       [2018-08-13 lun. 10:48]

voir par exemple le site de Neil Mitchell

https://ndmitchell.com/

voir aussi le petit coup de javaScript pour afficher tous les
abstracts et citations.  =Show all abstracts or citations.=

les sources de son site perso :
- https://github.com/ndmitchell/website
- https://github.com/ndmitchell/shake-website
