---
published: 2014-12-01
title: software
---
* professional activity
I am the main maintainer of deGoal, a tool for the design of runtime code generators, also called [[https://hpcharles.wordpress.com/softwares/][`compilettes`]]. deGoal is the property of CEA and not released publicly at this time. For further information, please reach me and/or can check my list of publications.

deGoal is the core technology used in [[http://www.cogito-anr.fr/][COGITO]], a research project that studies the potential of runtime code generation for security purposes in embedded devices.

* pet projects

Currently, I most enjoy writing code in Haskell even though I still consider myself as a beginner.
I have no public projects written in Haskell, except for this website, which is supported by [[http://jaspervdj.be/hakyll][Hakyll]].

Here is the list of my (public) pet projects, or former software projects I
have contributed to.

+ [[http://obnam.org/][obnam]] - a backup program capable of data de-duplication together with
  client-side encryption
+ [[http://sousmonlit.zincube.net/~niol/playa/oss/projects/lazygal][lazygal]] - a static web gallery generator written in Python

You can checkout my [[https://github.com/damiencourousse][github]] and [[https://bitbucket.org/damien_courouss/][bitbucket]] accounts.

#+COMMENT: smtps-gmail
#+COMMENT: inkscapeslide
#+COMMENT: mailtom

