---
title: generating page contents from org-mode files
---

The markdown format is nice, but considering that I extensively use
[[http://orgmode.org][OrgMode]], I investigated a bit to use org-mode files for generating the
contents of this website.
Indeed, org-mode files are supported by pandoc since version 1.12,
which has been integrated in [[http://jaspervdj.be/hakyll/releases.html][hakyll 4.5.2]].

* Generation of pages from org-mode files

This is straightforward.
Here is an example of a simple build rule for Hakyll:

#+BEGIN_SRC Haskell
    -- Static pages
    match "pages/*.org" $ do
        route $ gsubRoute "pages/" (const "") `composeRoutes` setExtension "html"
        compile $ do
            pandocCompiler
                >>= loadAndApplyTemplate "templates/default.html" defaultContext
                >>= relativizeUrls
#+END_SRC

* Metadata

Metadata are defined in an org-mode file with a dedicated format :

#+BEGIN_EXAMPLE
#FILE: mypage.org
#+TITLE: A page title
#+END_EXAMPLE

However, org-mode metadata are not recognised by Hakyll, especially if
you want to exploit metadata in your build system.
To do so, you need to [[http://jaspervdj.be/hakyll/tutorials/02-basics.html#pages-and-metadata][create a metadata file]] that will describe your
metadata with the syntax used by Hakyll, or to add a metadata header
in the org-mode file:

#+BEGIN_EXAMPLE
#FILE: mypage.org.metadata
---
title: A page title
---
#+END_EXAMPLE

When such a metadata header is used, its contents override the
org-mode metadata values.


